[MPIPreferences]
_format = "1.0"
abi = "MPICH"
binary = "system"
libmpi = "libmpi_cray"
mpiexec = "srun"
iscray = "true"

[CUDA_Runtime_jll]
version = "local"

[GPUCompiler]
disk_cache = "false"
cache_key = "Oceananigans"
