[MPIPreferences]
_format = "1.0"
abi = "OpenMPI"
binary = "system"
libmpi = "libmpi"
mpiexec = "srun"

[CUDA_Runtime_jll]
version = "local"

[GPUCompiler]
disk_cache = "true"
cache_key = "Oceananigans"