[MPIPreferences]
_format = "1.0"
abi = "OpenMPI"
binary = "system"
libmpi = "/storage4/simone/TestsScaling/openmpi/lib/libmpi.so"
mpiexec = "/storage4/simone/TestsScaling/openmpi/bin/mpiexec"

[CUDA_Runtime_jll]
version = "local"
